"""Fixed, non-CLI settings for the public CIFAR-10/VGG example."""

DATASET = "cifar10"
MODEL = "vgg16"
NUM_CLASSES = 10
NUM_CHANNELS = 3
IMAGE_SIZE = 32

PRUNING_START_MIN = 4
PRUNING_START_MAX = 13
PRUNING_RATIO_MIN = 0.2
PRUNING_RATIO_MAX = 0.7
PRUNING_RATIO_STEP = 0.1

MIN_DENSITY = 0.3
MAX_DENSITY = 0.8
TARGET_DENSITY = 0.6
FULL_MODEL_FASTEST_CLIENTS = 1

# The proposed channel selector: no stochastic channel exploration.
IMPORTANCE_SELECTION_RATIO = 0.8
COVERAGE_SELECTION_RATIO = 0.2
IMPORTANCE_EMA = 0.5

RESOURCE_SEED = 7
BITS_PER_PARAMETER = 32

SGD_MOMENTUM = 0.5
SGD_WEIGHT_DECAY = 1e-4
LEARNING_RATE_DECAY = 0.998

PROJECTION_FLOPS_WEIGHT = 0.5
PROJECTION_PARAMETERS_WEIGHT = 0.5
PROJECTION_OVERFLOW_PENALTY = 10.0
PROJECTION_TIME_PENALTY = 10.0
